### ISSUE TITLE
write to buffer instead of file

### ISSUE THREAD

**Issue by Pomax** [RickCraig/node-tiff-to-png#13]
Is there a way to not write anything to file when converting? Especially in limited-sized filesystems (e.g. droplets etc) it might be slower, but more preferable, to do the conversion in memory, returning a buffer than can then be sent out.

**Comment by RickCraig** [comment]
This module is really only an interface in node to call convert on the command line. The convert CLI doesn't have the option to return a Buffer or Blob. MagickCore has `ImageToBlob` in its API so it's not impossible if you can find a module that uses the API instead of the Convert CLI.

ref: [API Docs](https://www.imagemagick.org/api/blob.php)

**Comment by Pomax** [comment]
Noted. For anyone else finding this in the future, in order to achieve in-memory conversion I've switched from IM to the [sharp](https://www.npmjs.com/package/sharp). You give up all the power and speed of IM of course, but if you really just need it for TIFF conversion, that'll at least be an option to consider.
